### ISSUE TITLE
[Usersnap] Should this not be List<Article> instead of Task<string>?

### ISSUE THREAD

**Issue by epicodus-it** [epicodus-curriculum/c-sharp-full-stack#14]
Usersnap feedback [5044](https://app.usersnap.com/l/feedback/b6ddbc85-4188-4ec3-8f62-2e04eeb6fbed?utm_medium=integration&utm_campaign=integration&utm_content=open):

URL: https://full-time-pre-october.learnhowtoprogram.com/c-and-net/authentication-with-identity/api-calls-in-an-aspnet-core-mvc-app

Text: Should this not be List<Article> instead of Task<string>?

Screenshot: https://resources.usersnap.com/company/e2ef6bfd-aefd-493c-be03-42655e35a11f/datapoint_screenshot/3674538c-ed33-413a-81b5-66a2074f24d3-annotated_3b78d73c-9c61-4b5b-afe7-9a6767630e12.png?etag=50ba3781ec9019e39a62040932170bb6

**Comment by RyanDuff613** [comment]
This issue is addressed by [this PR](https://github.com/epicodus-curriculum/c-sharp-full-stack/pull/19).
