### ISSUE TITLE
[Usersnap] Area in box missing the word "make" as in "take a moment to make an API call"

### ISSUE THREAD

**Issue by epicodus-it** [epicodus-curriculum/c-sharp-full-stack#15]
Usersnap feedback [5054](https://app.usersnap.com/l/feedback/2e98e70f-bf29-4fcb-8e9e-a412473e7cc4?utm_medium=integration&utm_campaign=integration&utm_content=open):

URL: https://full-time-pre-october.learnhowtoprogram.com/c-and-net/authentication-with-identity/deserializing-api-responses-with-newtonsoftjson

Text: Area in box missing the word "make" as in "take a moment to make an API call"

Screenshot: https://resources.usersnap.com/company/e2ef6bfd-aefd-493c-be03-42655e35a11f/datapoint_screenshot/6f65bf25-ac00-436e-afdc-e262f768931c-annotated_ef496add-94f1-4cb7-85ff-f6ea80ff578e.png?etag=7703d3e8d22c89b1c138b50e101a1c72

**Comment by ashgoren** [comment]
fixed
