### ISSUE TITLE
[Usersnap] "our" should be "out"

### ISSUE THREAD

**Issue by epicodus-it** [epicodus-curriculum/c-sharp-full-stack#16]
Usersnap feedback [5055](https://app.usersnap.com/l/feedback/1902ec5c-ca5b-41e3-869b-690de42ee30d?utm_medium=integration&utm_campaign=integration&utm_content=open):

URL: https://part-time-evening.learnhowtoprogram.com/c-and-net/authentication-with-identity/the-identity-model

Text: "our" should be "out"

Screenshot: https://resources.usersnap.com/company/e2ef6bfd-aefd-493c-be03-42655e35a11f/datapoint_screenshot/b1b00c51-aef1-4b05-96c6-c38259082e4e-annotated_fe11945e-cdb8-4561-ba2d-ace04752ddc7.png?etag=843ee9d1a6f635f751e4eff36ef2686b

**Comment by RyanDuff613** [comment]
This issue is addressed by [this PR](https://github.com/epicodus-curriculum/c-sharp-full-stack/pull/19).
