### ISSUE TITLE
[Usersnap] strangely worded

### ISSUE THREAD

**Issue by epicodus-it** [epicodus-curriculum/c-sharp-full-stack#17]
Usersnap feedback [5056](https://app.usersnap.com/l/feedback/fdc44e77-0b1d-4c1a-9678-197056af5928?utm_medium=integration&utm_campaign=integration&utm_content=open):

URL: https://part-time-evening.learnhowtoprogram.com/c-and-net/authentication-with-identity/authentication-with-identity-user-registration-viewmodel-validation-and-views

Text: strangely worded

Screenshot: https://resources.usersnap.com/company/e2ef6bfd-aefd-493c-be03-42655e35a11f/datapoint_screenshot/5044a795-d317-446f-98f8-1d4fc0d6734f-annotated_33a0b622-9ecc-43a6-a449-58c48e5204c6.png?etag=d830dd67d8d235e6581e415e030e99fe

**Comment by RyanDuff613** [comment]
This issue is addressed by [this PR](https://github.com/epicodus-curriculum/c-sharp-full-stack/pull/19).
