### ISSUE TITLE
[Usersnap] we thought this was implying that we needed to use identity, when it was not expected of us. Maybe a rewording would help so we knew not to use authentication

### ISSUE THREAD

**Issue by epicodus-it** [epicodus-curriculum/c-sharp-full-stack#18]
Usersnap feedback [5059](https://app.usersnap.com/l/feedback/e6dceecf-efc6-41b5-bd34-33681df18930?utm_medium=integration&utm_campaign=integration&utm_content=open):

URL: https://full-time.learnhowtoprogram.com/c-and-net/building-an-api/building-an-api---part-1

Text: we thought this was implying that we needed to use identity, when it was not expected of us. Maybe a rewording would help so we knew not to use authentication

Screenshot: https://resources.usersnap.com/company/e2ef6bfd-aefd-493c-be03-42655e35a11f/datapoint_screenshot/078628d0-14e8-4af8-a8c1-565a3b9c3795-annotated_7e38cf2e-e3c2-46cb-bddb-c6c73173c70f.png?etag=a08dbcd8595e9e9148fc9b898574de30

**Comment by RyanDuff613** [comment]
This issue is addressed by [this PR](https://github.com/epicodus-curriculum/c-sharp-full-stack/pull/19).
