### ISSUE TITLE
[Usersnap] The following paragraph is repeated three times in a row on the page:  "Microsoft created the .NET Framework around the same time C# was developed. A framework like .NET provides built-in code and functionality, which makes writing code easier and more...

### ISSUE THREAD

**Issue by epicodus-it** [epicodus-curriculum/c-sharp-full-stack#23]
Usersnap feedback [5122](https://app.usersnap.com/l/feedback/5457bdba-fd88-4586-baf0-b01fb411fa91?utm_medium=integration&utm_campaign=integration&utm_content=open):

URL: https://full-time.learnhowtoprogram.com/c-and-net/getting-started-with-c/welcome-to-c

Text: The following paragraph is repeated three times in a row on the page:  "Microsoft created the .NET Framework around the same time C# was developed. A framework like .NET provides built-in code and functionality, which makes writing code easier and more...

Screenshot: https://resources.usersnap.com/company/e2ef6bfd-aefd-493c-be03-42655e35a11f/datapoint_screenshot/72724b1a-6ce1-4494-b515-105c3c777089-annotated_7096dc10-545d-4cc1-9c5d-7d88b37de4ef.png?etag=2f689bcebc49f452eb12bd0753586d76

**Comment by erik-t-irgens** [comment]
Thanks for the catch! Following up late, but it's been remedied already! :)
